#!/usr/bin/env bash

set -e

echo "copy dotfiles"
cp -r -v .* ~/

echo "copy git plugins"
cp -v git-* /usr/local/bin/

echo "image diff"
cp -v image-diff /usr/local/bin/

echo "install core stuff"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
sh -c "$(curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh)"

echo "installing brew cask"
brew tap caskroom/cask

casks=(google-chrome alfred docker-beta bettertouchtool flux spotify sizeup)

for cask in ${casks[@]}; do
  echo "installing $cask"
  brew cask install $cask
done

installs=(node yarn)

for install in ${installs[@]}; do
  echo "installing $install"
  brew install $install
done

echo "configure yarn"
yarn config set save-prefix ''

echo "configure npm and yarn"
yarn config set save-prefix ''
npm config set save-exact true

echo "installing npm modules"
export NODE_PATH="/usr/local/lib/node_modules"
npm install n pkginit osx-wifi-cli standard pkginit picture-tube npmrc -g

echo "configure pkginit"
mkdir -p .config/pkginit/
cp pkginit.json ~/.config/pkginit/default

echo "configure zshrc"
mkdir -p ~/Documents/src
cd ~/Documents/src
git clone git@github.com:JamesKyburz/zsh_stuff.git

echo "configure vim"
git clone https://github.com/vim/vim.git
cd vim
make distclean
make
sudo make install
vim +NeoBundleInstall +qall

echo "configure osx"
~/.osx
